routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\StudentController;
use App\Http\Middleware\CheckLogin;

Route::get('/login', [LoginController::class, "login"])->name("login");
Route::post('/login-process', [LoginController::class, "loginProcess"])->name("login-process");

Route::middleware([CheckLogin::class])->group(function () {
    Route::get('/logout', [LoginController::class, "logout"])->name('logout');

    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    // Quản lý lớp => CRUD 
    Route::resource('grade', GradeController::class);

    // Quản lý sinh viên => CRUD 
    Route::resource('student', StudentController::class);
});

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Phan Mai Duyeen</title>
    <!-- Bootstrap core CSS     -->
    <link href="{{ asset('assets') }}/css/bootstrap.min.css" rel="stylesheet" />

    <!--  Paper Dashboard core CSS    -->
    <link href="{{ asset('assets') }}/css/paper-dashboard.css" rel="stylesheet" />


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{{ asset('assets') }}/css/demo.css" rel="stylesheet" />


    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{{ asset('assets') }}/css/themify-icons.css" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        @include('layout.menu')
        <div class="main-panel">
            <div class="content">
                <div class="container-fluid">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>

    <!--   Core JS Files. Extra: TouchPunch for touch library inside jquery-ui.min.js   -->
    <script src="{{ asset('assets') }}/js/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="{{ asset('assets') }}/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="{{ asset('assets') }}/js/perfect-scrollbar.min.js" type="text/javascript"></script>
    <script src="{{ asset('assets') }}/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  Forms Validations Plugin -->
    <script src="{{ asset('assets') }}/js/jquery.validate.min.js"></script>

    <!-- Promise Library for SweetAlert2 working on IE -->
    <script src="{{ asset('assets') }}/js/es6-promise-auto.min.js"></script>

    <!--  Plugin for Date Time Picker and Full Calendar Plugin-->
    <script src="{{ asset('assets') }}/js/moment.min.js"></script>

    <!--  Date Time Picker Plugin is included in this js file -->
    <script src="{{ asset('assets') }}/js/bootstrap-datetimepicker.js"></script>

    <!--  Select Picker Plugin -->
    <script src="{{ asset('assets') }}/js/bootstrap-selectpicker.js"></script>

    <!--  Switch and Tags Input Plugins -->
    <script src="{{ asset('assets') }}/js/bootstrap-switch-tags.js"></script>

    <!-- Circle Percentage-chart -->
    <script src="{{ asset('assets') }}/js/jquery.easypiechart.min.js"></script>

    <!--  Charts Plugin -->
    <script src="{{ asset('assets') }}/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="{{ asset('assets') }}/js/bootstrap-notify.js"></script>

    <!-- Sweet Alert 2 plugin -->
    <script src="{{ asset('assets') }}/js/sweetalert2.js"></script>

    <!-- Vector Map plugin -->
    <script src="{{ asset('assets') }}/js/jquery-jvectormap.js"></script>

    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Wizard Plugin    -->
    <script src="{{ asset('assets') }}/js/jquery.bootstrap.wizard.min.js"></script>

    <!--  Bootstrap Table Plugin    -->
    <script src="{{ asset('assets') }}/js/bootstrap-table.js"></script>

    <!--  Plugin for DataTables.net  -->
    <script src="{{ asset('assets') }}/js/jquery.datatables.js"></script>

    <!--  Full Calendar Plugin    -->
    <script src="{{ asset('assets') }}/js/fullcalendar.min.js"></script>

    <!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
    <script src="{{ asset('assets') }}/js/paper-dashboard.js"></script>

    <!-- Paper Dashboard PRO DEMO methods, don't include it in your project! -->
    <script src="{{ asset('assets') }}/js/demo.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            demo.initChartsPage();
        });
    </script>
</body>

</html>

resources/views/layout/menu.blade.php
<div class="sidebar" data-background-color="brown" data-active-color="danger">

    <div class="logo">
        <a href="http://www.creative-tim.com" class="simple-text logo-mini">
            CT
        </a>

        <a href="http://www.creative-tim.com" class="simple-text logo-normal">
            Creative Tim
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <img src="../assets/img/faces/face-2.jpg" />
            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    <span>
                        Chet Faker
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="clearfix"></div>

                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <li>
                            <a href="#profile">
                                <span class="sidebar-mini">Mp</span>
                                <span class="sidebar-normal">My Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="#edit">
                                <span class="sidebar-mini">Ep</span>
                                <span class="sidebar-normal">Edit Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="#settings">
                                <span class="sidebar-mini">S</span>
                                <span class="sidebar-normal">Settings</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li>
                <a href="#dashboardOverview">
                    <i class="ti-panel"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a href="{{ route('grade.index') }}">
                    <i class="ti-package"></i>
                    <p>Quản lý love</p>
                </a>
            </li>
            <li>
                <a href="{{ route('student.index') }}">
                    <i class="ti-clipboard"></i>
                    <p>
                        Quản lý sinh vin
                    </p>
                </a>
            </li>
        </ul>
    </div>
</div>