routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\StudentController;
use App\Http\Middleware\CheckLogin;

Route::get('/login', [LoginController::class, "login"])->name("login");
Route::post('/login-process', [LoginController::class, "loginProcess"])->name("login-process");

Route::middleware([CheckLogin::class])->group(function () {
    Route::get('/logout', [LoginController::class, "logout"])->name('logout');

    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    // Quản lý lớp => CRUD 
    Route::resource('grade', GradeController::class);

    // Quản lý sinh viên => CRUD 
    Route::resource('student', StudentController::class);
});

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $table = 'student';

    public $timestamps = false;

    public $primaryKey = 'idStudent';

    public function getGenderNameAttribute()
    {
        if ($this->gender == 0) {
            return 'Nữ';
        } else {
            return 'Nam';
        }
    }

    public function getFullNameAttribute()
    {
        return $this->lastName . ' ' . $this->firstName;
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use App\Models\Grade;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listStudent = Student::all();
        return view('student.index', [
            "listStudent" => $listStudent
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        $listGrade = Grade::all();

        return view('student.edit', [
            "student" => $student,
            "listGrade" => $listGrade,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student = Student::find($id);
        $student->firstName = $request->get('first-name');
        $student->lastName = $request->get('last-name');
        $student->gender = $request->get('gender');
        $student->dateBirth = $request->get('date-birth');
        $student->idGrade = $request->get('id-grade');
        $student->save();
        return Redirect::route('student.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Student::find($id)->delete();
        return Redirect::route('student.index');
    }
}

resources/views/student/edit.blade.php
@extends('layout.app')

@section('content')
    <h1>Sửa điiiii</h1>

    <form action="{{ route('student.update', $student->idStudent) }}" method="post">
        @method('PUT')
        @csrf
        Tên: <input type="text" name="first-name" value="{{ $student->firstName }}">
        <br>
        Họ: <input type="text" name="last-name" value="{{ $student->lastName }}">
        <br>
        Giới tính: <input type="radio" name="gender" value="1" @if ($student->gender == 1) checked @endif>
        Nam
        <input type="radio" name="gender" value="0" @if ($student->gender == 0) checked @endif>
        Nữ
        <br>
        Ngày sinh: <input type="date" name="date-birth" value="{{ $student->dateBirth }}">
        <br>
        Lớp: <select name="id-grade">
            @foreach ($listGrade as $grade)
                <option value="{{ $grade->idGrade }}" @if ($student->idGrade == $grade->idGrade) selected @endif>
                    {{ $grade->nameGrade }}
                </option>
            @endforeach
        </select>
        <br>
        <button>Ok</button>
    </form>

@endsection

resources/views/student/index.blade.php
@extends('layout.app')

@section('content')
    <table>
        <tr>
            <th>Mã</th>
            <th>Họ Tên</th>
            <th>Giới tính</th>
            <th>Ngày sinh</th>
            <th>Lớp</th>
            <th>Sửa</th>
            <th>Xóa</th>
        </tr>
        @foreach ($listStudent as $student)
            <tr>
                <td>{{ $student->idStudent }}</td>
                <td>{{ $student->FullName }}</td>
                <td>{{ $student->GenderName }}</td>
                <td>{{ $student->dateBirth }}</td>
                <td>{{ $student->idGrade }}</td>
                <td>
                    <a href="{{ route('student.edit', $student->idStudent) }}">
                        Sửa
                    </a>
                </td>
                <td>
                    <form action="{{ route('student.destroy', $student->idStudent) }}" method="post">
                        @method('DELETE')
                        @csrf
                        <button>Xóa</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection