routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\StudentController;
use App\Http\Middleware\CheckLogin;

Route::get('/login', [LoginController::class, "login"])->name("login");
Route::post('/login-process', [LoginController::class, "loginProcess"])->name("login-process");

Route::middleware([CheckLogin::class])->group(function () {
    Route::get('/logout', [LoginController::class, "logout"])->name('logout');

    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    // Quản lý lớp => CRUD 
    Route::resource('grade', GradeController::class);

    // Quản lý sinh viên => CRUD 
    Route::resource('student', StudentController::class);
});

app/Models/Grade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    use HasFactory;

    protected $table = 'grade';

    public $timestamps = false;

    public $primaryKey = 'idGrade';
}

app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Grade;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class GradeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        // $listGrade = Grade::all(); # lấy tất cả dữ liệu
        $listGrade = Grade::where('nameGrade', 'like', "%$search%")->paginate(3);

        return view('grade.index', [
            "listGrade" => $listGrade,
            "search" => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('grade.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Nhận dữ liệu
        $name = $request->get('name');
        // DB::table('grade')->insert([
        //     "nameGrade" => $name,
        // ]);
        $grade = new Grade();
        $grade->nameGrade = $name;
        $grade->save();

        // return redirect(route('grade.index'));
        // return redirect()->route('grade.index'); # bản cũ
        return Redirect::route('grade.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $grade = Grade::where("idGrade", $id)->first(); # where
        // model find
        $grade = Grade::find($id);
        return $grade;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

resources/views/grade/create.blade.php
@extends('layout.app')

@section('content')
    <h1>Thêm lớp ikkkkk</h1>

    <form action="{{ route('grade.store') }}" method="post">
        @csrf
        Tên lớp: <input type="text" required name="name">
        <br>
        <button>Đi đi</button>
    </form>
@endsection

resources/views/grade/index.blade.php
@extends('layout.app')

@section('content')
    <h1>Danh sách love</h1>
    <a href="{{ route('grade.create') }}">Thêm love</a>

    <form action="" method="get">
        <input type="text" name="search" value="{{ $search }}">
        <button>Tìm nó</button>
    </form>

    <table>
        <tr>
            <th>Mã</th>
            <th>Tên</th>
            <th>Xem</th>
            <th>Sửa</th>
            <th>Xóa</th>
        </tr>
        @foreach ($listGrade as $grade)
            <tr>
                <td>{{ $grade->idGrade }}</td>
                <td>{{ $grade->nameGrade }}</td>
                <td><a href="{{ route('grade.show', $grade->idGrade) }}">Xem</a></td>
                <td></td>
                <td></td>
            </tr>
        @endforeach
    </table>

    {{ $listGrade->appends([
        'search' => $search,
    ])->links() }}
@endsection